---
{{- if .Values.service.createService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oraclexe.nameWithSuffix" (dict "context" . "suffix" .Values.service.name) }}
  namespace: {{ .Values.namespace.name }}
{{- if .Values.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
{{- end }}
  labels:
{{ include "oraclexe.selectorLabels" . | indent 4 }}
spec:
  ports:
    - name: 1521-tcp
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: 5500-tcp
      port: 5500
      protocol: TCP
      targetPort: 5500
  selector:
{{ toYaml .Values.service.selector | indent 4 }}
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
{{- end }}